---
apiVersion: v1
kind: Namespace
metadata:
  name: openebs-localpv
---
apiVersion: source.toolkit.fluxcd.io/v1beta2
kind: HelmRepository
metadata:
  name: openebs-localpv
  namespace: flux-system
spec:
  interval: 6h
  url: https://openebs.github.io/dynamic-localpv-provisioner
---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: openebs-localpv
  namespace: flux-system
spec:
  serviceAccountName: kustomize-controller
  interval: 6h
  chart:
    spec:
      chart: localpv-provisioner
      version: '3.3.x'
      sourceRef:
        kind: HelmRepository
        name: openebs-localpv
      interval: 6h
  targetNamespace: openebs-localpv
  values:
    openebsNDM:
      enabled: false
    deviceClass:
      enabled: false
    hostpathClass:
      basePath: /mnt/data/openebs
      isDefaultClass: true
      xfsQuota:
        enabled: true
    analytics:
      enabled: false
