apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
# Flux
- ../../manifests/system/flux
- manifests/flux/fleet-infra.yaml
- manifests/flux/fleet-infra.secret.yaml
- ../../manifests/system/flux/notification
